version: 0.2

phases:
  install:
    commands:
      - "wget https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip"
      - "unzip terraform_1.2.5_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - |
          if [ "$STEP" = "plan" ]; then
            terraform plan
          elif [ "$STEP" = "apply" ]; then
            terraform apply --auto-approve
          fi